version: "3.8"

services:
  application:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: application
    container_name: application
    volumes:
      - ./:/app/
    ports:
      - 7860:7860
    networks:
      - net
    depends_on:
      - chroma

  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    container_name: database
    volumes:
      - index_data:/chroma/.chroma/index
    ports:
      - 8000:8000
    networks:
      - net

volumes:
  index_data:
    driver: local
  backups:
    driver: local

networks:
  net:
    driver: bridge